# Generated by Django 5.2.17 on 2026-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_theme', models.CharField(choices=[('editorial', 'Éditorial (Libre Bodoni / Public Sans)'), ('modern', 'Moderne (Inter)'), ('classic', 'Classique (Playfair Display / Source Sans 3)')], default='editorial', help_text="Police utilisée sur l'ensemble du site.", max_length=20)),
                ('color_theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', help_text="Thème de couleur utilisé sur l'ensemble du site.", max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Format international, ex : +33612345678', max_length=20)),
                ('youtube_url', models.URLField(blank=True, help_text='Lien vers la chaîne YouTube.')),
                ('facebook_url', models.URLField(blank=True, help_text='Lien vers la page Facebook.')),
                ('demo_url', models.URLField(blank=True, help_text='Lien vers la démo des produits.')),
                ('presentation_video_url', models.URLField(blank=True, help_text="Lien YouTube de la vidéo de présentation (affichée sur l'accueil).")),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
    ]
