# Generated by Django 5.2.17 on 2026-09-22 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Format international, ex : +33612345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro invalide. Utilisez un format international, ex : +33612345678 (8 à 15 chiffres, espaces autorisés).', regex='^\\+?[\\d\\s]{8,20}$')]),
        ),
    ]
